package com.unl.practica2.base.models;

public enum RolArtistaEnum {
    SOLISTA, VOCALISTA, GUITARRISTA, BAJISTA, BATERISTA, TECLADISTA, SAXOFONISTA, TRUMPETISTA, PERCUSIONISTA,
    VIOLINISTA, VIOLONCELISTA, CHELISTA, MANDOLINISTA, FLAUTISTA, CLARINETISTA, TROMBONISTA, HARMONICISTA, CANTANTE

}
